export const language = [
  { Id: 'KR', country: '대한민국', lang: '한국어' },
  { Id: 'US', country: 'United States', lang: 'English' },
  { Id: 'UK', country: 'United Kingdom', lang: 'English' },
  { Id: 'ID', country: 'Indonesia', lang: 'Bahasa Indonesia' },
  { Id: 'MY', country: 'Malaysia', lang: 'Bahasa Melayu' },
  { Id: 'CZ', country: 'Czech Republic', lang: 'Čeština' },
  { Id: 'DK', country: 'Denmark', lang: 'Dansk' },
  { Id: 'DE', name: 'Germany', lang: 'Deutsch' },
  { Id: 'ES', country: 'Spain', lang: 'Español' },
  { Id: 'MX', country: 'Mexico', lang: 'Español' },
  { Id: 'PH', country: 'Philippines', lang: 'Filipino' },
  { Id: 'FR', country: 'France', lang: 'Français' },
  { Id: 'IT', country: 'Italy', lang: 'Italiano' },
  { Id: 'HU', country: 'Hungary', lang: 'Magyar' },
  { Id: 'NL', country: 'Netherlands', lang: 'Nederlands' },
  { Id: 'NO', country: 'Norway', lang: 'Norsk, Bokmål' },
  { Id: 'PL', country: 'Poland', lang: 'Polski' },
  { Id: 'BR', country: 'Brazil', lang: 'Português' },
  { Id: 'PT', country: 'Portugal', lang: 'Português' },
  { Id: 'RO', country: 'Romania', lang: 'Română' },
  { Id: 'FI', country: 'Finland', lang: 'Suomi' },
  { Id: 'SE', country: 'Sweden', lang: 'Svenska' },
  { Id: 'VN', country: 'Vietnam', lang: 'Tiếng Việt' },
  { Id: 'TR', country: 'Turkey', lang: 'Türkçe' },
  { Id: 'GR', country: 'Greece', lang: 'Ελληνικά' },
  { Id: 'RU', country: 'Russia', lang: 'Русский' },
  { Id: 'UA', country: 'Ukraine', lang: 'Українська' },
  { Id: 'TH', country: 'Thailand', lang: 'ไทย' },
  { Id: 'JP', country: 'Japan', lang: '日本語' },
  { Id: 'CN', country: 'China', lang: '简体中文' },
];

export const currency = [
  {
    Id: 'AU',
    name: 'Australia',
    currencyId: 'AUD',
    currency: '$',
    currencyName: '호주 달러',
  },
  {
    Id: 'BR',
    name: 'Brazil',
    currencyId: 'BRL',
    currency: 'R$',
    currencyName: '브라질 레알',
  },
  {
    Id: 'BG',
    name: 'Bulgaria',
    currencyId: 'BGN',
    currency: 'лв',
    currencyName: '블라리아 레프',
  },
  {
    Id: 'CA',
    name: 'Canada',
    currencyId: 'CAD',
    currency: '$',
    currencyName: '캐나다 달러',
  },
  {
    Id: 'CL',
    name: 'Chile',
    currencyId: 'CLP',
    currency: '$',
    currencyName: '칠레 페소',
  },
  {
    Id: 'CN',
    name: 'China',
    currencyId: 'CNY',
    currency: '￥',
    currencyName: '중국 위안',
  },
  {
    Id: 'CO',
    name: 'Colombia',
    currencyId: 'COP',
    currency: '$',
    currencyName: '콜롬비아 페소',
  },
  {
    Id: 'CR',
    name: 'Costa Rica',
    currencyId: 'CRC',
    currency: '₡',
    currencyName: '코스타리카 콜론',
  },
  {
    Id: 'HR',
    name: 'Croatia',
    currencyId: 'HRK',
    currency: 'kn',
    currencyName: '크로아티아 쿠나',
  },
  {
    Id: 'CZ',
    name: 'Czech Republic',
    currencyId: 'CZK',
    currency: 'Kč',
    currencyName: '체코 코루나',
  },
  {
    Id: 'DK',
    name: 'Denmark',
    currencyId: 'DKK',
    currency: 'kr',
    currencyName: '덴마크 크로네',
  },
  {
    Id: 'AE',
    name: 'United Arab Emirates',
    currencyId: 'AED',
    currency: 'ﺩ.ﺇ',
    currencyName: '아랍에미리트 디르함',
  },
  { currencyId: 'EUR', currency: '€', currencyName: '유로' },
  {
    Id: 'HK',
    name: 'Hong Kong',
    currencyId: 'HKD',
    currency: '$',
    currencyName: '홍콩 달러',
  },
  {
    Id: 'HU',
    name: 'Hungary',
    currencyId: 'HUF',
    currency: 'Ft',
    currencyName: '헝가리 포린트',
  },
  {
    Id: 'IN',
    name: 'India',
    currencyId: 'INR',
    currency: '₹',
    currencyName: '인도 루피',
  },
  {
    Id: 'IL',
    name: 'Israel',
    currencyId: 'ILS',
    currency: '₪',
    currencyName: '이스라엘 신 셰켈',
  },
  {
    Id: 'JP',
    name: 'Japan',
    currencyId: 'JPY',
    currency: '¥',
    currencyName: '일본 엔',
  },
  {
    Id: 'MY',
    name: 'Malaysia',
    currencyId: 'MYR',
    currency: 'RM',
    currencyName: '말레이시아 링깃',
  },
  {
    Id: 'MX',
    name: 'Mexico',
    currencyId: 'MXN',
    currency: '$',
    currencyName: '멕시코 페소',
  },
  {
    Id: 'MA',
    name: 'Morocco',
    currencyId: 'MAD',
    currency: 'MAD',
    currencyName: '모로코 디르함',
  },
  {
    Id: 'TW',
    name: 'Taiwan',
    currencyId: 'TWD',
    currency: '$',
    currencyName: '신 타이완 달러',
  },
  {
    Id: 'NZ',
    name: 'New Zealand',
    currencyId: 'NZD',
    currency: '$',
    currencyName: '뉴질랜드 달러',
  },
  {
    Id: 'NO',
    name: 'Norway',
    currencyId: 'NOK',
    currency: 'kr',
    currencyName: '노르웨이 크로네',
  },
  {
    Id: 'PE',
    name: 'Peru',
    currencyId: 'PEN',
    currency: 'S/',
    currencyName: '페루 솔',
  },
  {
    Id: 'PH',
    name: 'Philippines',
    currencyId: 'PHP',
    currency: '₱',
    currencyName: '필리핀 페소',
  },
  {
    Id: 'PL',
    name: 'Poland',
    currencyId: 'PLN',
    currency: 'zł',
    currencyName: '폴란드 즐로티',
  },
  {
    Id: 'UK',
    name: 'United Kingdom',
    currencyId: 'GBP',
    currency: '£',
    currencyName: '영국 파운드',
  },
  {
    Id: 'RO',
    name: 'Romania',
    currencyId: 'RON',
    currency: 'lei',
    currencyName: '루마니아 레우',
  },
  {
    Id: 'RU',
    name: 'Russia',
    currencyId: 'RUB',
    currency: '₽',
    currencyName: '러시아 루블',
  },
  {
    Id: 'SA',
    name: 'Saudi Arabia',
    currencyId: 'SAR',
    currency: 'SR',
    currencyName: '사우디아라비아 리얄',
  },
  {
    Id: 'SG',
    name: 'Singapore',
    currencyId: 'SGD',
    currency: '$',
    currencyName: '싱가포르 달러',
  },
  {
    Id: 'ZA',
    name: 'South Africa',
    currencyId: 'ZAR',
    currency: 'R',
    currencyName: '남아프리카공화국 란드',
  },
  {
    Id: 'KR',
    name: 'South Korea',
    currencyId: 'KRW',
    currency: '₩',
    currencyName: '한국 원',
  },
  {
    Id: 'SE',
    name: 'Sweden',
    currencyId: 'SEK',
    currency: 'kr',
    currencyName: '스웨덴 크로나',
  },
  {
    Id: 'CH',
    name: 'Switzerland',
    currencyId: 'CHF',
    currency: 'CHF',
    currencyName: '스위스 프랑',
  },
  {
    Id: 'TH',
    name: 'Thailand',
    currencyId: 'THB',
    currency: '฿',
    currencyName: '태국 바트',
  },
  {
    Id: 'TR',
    name: 'Turkey',
    currencyId: 'TRY',
    currency: '₺',
    currencyName: '터키 리라',
  },
  {
    Id: 'US',
    name: 'United States',
    currencyId: 'USD',
    currency: '$',
    currencyName: '미국 달러',
  },
];
